### ISSUE TITLE
More clarification on parameters

### ISSUE THREAD

**Issue by yaxu** [kousheekc/Kinematics#5] opened 2022-05-17 12:45 UTC
Hi again, I now have an arduino mega and the code is running. I've been studying the example code and the video you've pointed at about calculating the screw axes but not quite understanding everything yet.. In my attempts to use the library, I either get all zeroes out, or some very large numbers indeed. I wondered if you could have a look at what I'm trying to do and offer any tips.

In the joints in the example:

https://github.com/kousheekc/Kinematics/blob/c045e3ce1bfa492b18a9c11d40b950ea273b7338/examples/inverse_kinematics/inverse_kinematics.ino#L13-L15

Am I right that the second joint does not specify an axis (first three numbers are zeroes)? I'm a bit confused about what that means if so.

I'm trying with this, taking the first axis as the origin:
```c
    kin.add_joint_axis(0, 1,  0, 0, 0, 0);
    kin.add_joint_axis(1, 0, 0, 0, 0, 68);
    kin.add_joint_axis(0, 0, 1, 0, 0, 114);
```
To describe these three ax12a servos:
![image](https://user-images.githubusercontent.com/27940/168808024-13309bb1-5114-4eb9-ba86-49d49797bebd.png)

An ASCII art sketch showing the orientation.. :)
```
     ___
    |o o|
    :___: 
   .--u--.
   |.---.|
   |=   =|
    |   | 
    |___|
    ,| |.
    ||o||     z y
    | - |     |/
     ---      `--x
```
Now I'm a little confused about how to describe it's initial pose. Here's my attempt at describing where its 'nose' is (where the QC sticker is in the photo..) at the start:
```c
    kin.add_initial_end_effector_pose(1, 0, 0, 0,
                                      0, 1, 0, -38,
                                      0, 0, 1, 114,
                                      0, 0, 0, 1
                                     );
```
... so given that, to attempt to move the end effector 10mm in the x direction, would it be:
```c
    float desired_transform[4][4] = {
        {1, 0,  0, 10},
        {0, 1,  0, 0},
        {0, 0,  1, 0},
        {0, 0,  0, 1}
    };
```

I'm also unclear on what the `joint_angles_0` should be set to.

Here's what I'm currently trying:
```c
#include <Dynamixel2Arduino.h>
#include "Kinematics.h"
#include "MatrixUtils.h"
#include <SoftwareSerial.h>

#define joints 3

SoftwareSerial soft_serial(7, 8);
//#define DEBUG_SERIAL soft_serial  
//#define debug DEBUG_SERIAL.println
#define DEBUG_SERIAL Serial  
#define debug Serial.println
Dynamixel2Arduino dxl(Serial, 2);

void debug_matrix(float* mat, int r, int c, String message) { 
    debug(message);
    for (int i = 0; i < r; i++) {
        for (int j = 0; j < c; j++) {
            debug(mat[c * i + j]);
            debug("\t");
        }
        debug();
    }
    debug();
}


void setup() {
  // put your setup code here, to run once:
  //Serial.begin(9600);
  DEBUG_SERIAL.begin(9600);
  while(!DEBUG_SERIAL); // wait until open  
  debug("hello from setup()");
    Kinematics kin(joints);
    MatrixUtils mat_utils;

/*
     ___
    |o o|
    :___: 
   .--u--.
   |.---.|
   |=   =|
    |   | 
    |___|
    ,| |.
    ||o||     z y
    | - |     |/
     ---      `--x
              
*/
  debug("add joints");

    // aligned with y axis
    // Treat the centre of the first axis as the origin?
    kin.add_joint_axis(0, 1,  0, 0, 0, 0);
    
    // joint aligned with x axis
    // 26 + 42 = 68mm above
    kin.add_joint_axis(1, 0, 0, 0, 0, 68);

    // aligned with z axis
    // 68 from previous, plus another 26.. and 20 for middle? = 114mm
    kin.add_joint_axis(0, 0, 1, 0, 0, 114);

    debug("add nose pose");
    // nose points -38mm out

    kin.add_initial_end_effector_pose(1, 0, 0, 0,
                                      0, 1, 0, -38,
                                      0, 0, 1, 114,
                                      0, 0, 0, 1
                                     );
//    kin.add_initial_end_effector_pose(1, 0, 0, 0,
//                                      0, 1, 0, 0,
//                                      0, 0, 1, 0,
//                                      0, 0, 0, 1
//                                     );
    float desired_transform[4][4] = {
        {1, 0,  0, 10},
        {0, 1,  0, 0},
        {0, 0,  1, 0},
        {0, 0,  0, 1}
    };

    float jac[6][joints];
    float jac_t[6][joints];
    float AA_t[6][6];
    float A_tA[joints][joints];
    float pinv[joints][6];

    float joint_angles_0[joints] = {0, 0, 0};
    //    float joint_angles_0[N] = {1.0, 2.5, 3}; // original..

    float joint_angles[joints] = {-1,-1,-1};

    debug("get the transform");
    kin.inverse((float*)desired_transform, (float*)jac, (float*)pinv, (float*)jac_t, (float*)AA_t, 
                (float*)A_tA, joint_angles_0, 0.01, 0.001, 20, joint_angles);
    debug("print the matrix");
    debug_matrix(joint_angles, 1, joints, "Joint angles");
    
}

void loop() {
}
```
Which gives these improbable joint angles:
```
4065740.00
25817456.00
-3239346.00
```

Any pointers would be much appreciated!

**Comment by kousheekc** [comment] 2022-05-18 08:05
Hi, glad to hear that the code worked on the Arduino Mega. Here is my attempt at resolving the issue that you are facing. I have added some annotations and markings to the picture you uploaded to help with the explanation.

![Inked168808024-13309bb1-5114-4eb9-ba86-49d49797bebd_LI](https://user-images.githubusercontent.com/25120991/168982853-8259e7c5-3353-4720-a0b9-dbfb5105f19a.jpg)

- The orange arrows represent the joints in your system (j1, j2, j3)
- The green frame represents the base frame
- The yellow frame represents the end-effector frame
- The red markings indicate the lengths of the links

Let's start with expressing the screw axes of each joint with respect to the base frame.

1. **Joint 1**: Since **j1** is aligned with the **negative y-axis** of the s frame, the first three values of the screw axis are **0, -1, 0**. And since a rotation about j1, does not induce a rotational movement of the base frame, the last three values of the screw axis are **0, 0, 0**. Therefore your first add_joint_axis command would be: `kin.add_joint_axis(0, -1, 0, 0, 0, 0);`
2. **Joint 2**: Since **j2** is aligned with the **negative x-axis** of the s frame, the first three values of the screw axis are **-1, 0, 0**. And since a rotation about j2, induces a rotational movement of the base frame of magnitude **4** along the **negative y** direction, the last three values of the screw axis are **0, -L1, 0**. Therefore your second add_joint_axis command would be: `kin.add_joint_axis(-1, 0, 0, 0, -L1, 0);`
3. **Joint 3**: Since **j3** is aligned with the **positive z-axis** of the s frame, the first three values of the screw axis are **0, 0, 1**. And since a rotation about j3, does not induce a rotational movement of the base frame, the last three values of the screw axis are **0, 0, 0**. Therefore your third add_joint_axis command would be: `kin.add_joint_axis(0, 0, 1, 0, 0, 0);`

The initial end-effector pose can be determined by studying the position and orientation of the end-effector frame with respect to the base frame. 

The orientation of the end-effector frame and base frame are the same. 
The position of the end-effector frame is:
- 0 along the x-axis
- -L3 along the y-axis
- L1 + L2 along the z-axis

Therefore you would have:
```
    kin.add_initial_end_effector_pose(1, 0, 0, 0,
                                      0, 1, 0, -L3,
                                      0, 0, 1, L1+L2,
                                      0, 0, 0, 1
                                     );
``` 

You could update the code with these changes and see if it works. Additionally, you could give the values of L1, L2, and L3, I could test it and see if the output makes sense.

I hope this helped.

**Comment by yaxu** [comment] 2022-05-18 08:20
Thanks so much @kousheekc! That's a really clear explanation. I might not be able to get back to my robot until tomorrow, but looking forward to trying this, I'll let you know how I get on.

**Comment by yaxu** [comment] 2022-05-19 14:23
Here's what the robot looks like when it's moving: https://photos.google.com/photo/AF1QipN8t3IpWOispEWjQxkbJhLmmmiHuoYZGvsuOLa7

I haven't fully grasped your example yet (e.g. how j1 doesn't move the base frame but j2 does..) but I've plugged those numbers in: https://gist.github.com/yaxu/ac6b2b42068f533d184ecfff38e03553

If I set the desired_transform to be the same as the initial end effector pose, it gives angles of 0,0,0, as expected.

If I adjust the y:
```c
    float desired_transform[4][4] = {
        {1, 0,  0, 0},
        {0, 1,  0, -(L3+10)},
        {0, 0,  1, L1+L2},
        {0, 0,  0, 1}
    };
```

It returns joint angles of `0.00, 0.15, 0.00`, which makes sense to me too.

If I adjust the x or z, it just returns 0,0,0 after 20 iterations though. Is this is the calculation failing?

Perhaps I need to adjust the error tolerances, because there are many points that this robot will not be able to reach in this configuration..

**Comment by kousheekc** [comment] 2022-05-19 18:23
You are right, the error tolerances need to be adjusted for the code to converge to some output.

The issue is that the top left 3x3 matrix of the desired transform represents the desired orientation of end-effector frame with respect to the base frame. And given a 3DOF kinematic chain, achieving an identity orientation (aligned with the base frame) while being offset along any axis is not possible.

You could solve this by increasing the first error tolerance (currently 0.01) to a larger value since this is responsible for the error tolerance in the orientation.

Another option would be to go into the source code where the inverse kinematics is computed and study the errors by doing some basic prints. This might give you a better idea of the magnitude of the error you are dealing with.

**Closed as completed** 2022-06-19 06:49 UTC
